directories:
  script: scripts
  module: scripts/modules
  test: scripts/tests

# Environment variables
env:
  DOCKER_SCOPE: "escapace"

# Enable manage repository scripts
enable:
  - help

# Default script
default: help
