# Environment variables
env:
  DOCKER_SCOPE: "escapace"
  GIT_USER_NAME: "escapace"
  GIT_USER_EMAIL: "security@escapace.com"
  GIT_USER_SIGNINGKEY: "0x90A65F3603169487"

# Enable manage repository scripts
enable:
  - help
  - trust-escapace

# Default script
default: help
