directories:
  script: scripts
  module: scripts/modules
  test: scripts/tests

# Environment variables
env:
  DOCKER_SCOPE: "epiloque"

# Enable manage repository scripts
enable:
  - help
  - test

# Default script
default: help
