# Relative path to the script directory
scripts: scripts

# Check for the following dependencies in PATH
dependencies:
  - bash
  - awk
  - sed
  - tr
  - head

# Environment variables
env:
  DOCKER_USERNAME: epiloque
  DOCKER_MAINTAINER: "Mark Milstein <mark@epiloque.com>"

# Enable scripts from manage repository
enable:
  - help

# Default script to execute
default: help

