sudo: required
dist: trusty
language: bash
addons:
  apt:
    packages:
    - bc
services:
- docker
env:
  global:
  - PATH="/usr/bin:$PATH"
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-ce
script:
- ./manage test
